### ISSUE TITLE
환불 영수증 조회 레이아웃 작성

### ISSUE THREAD

**Issue by yongwookbae** [umbum/convenience-store-POS-system#19]

**Comment by umbum** [comment]
좋습니다  
"환불 영수증 조회 레이아웃 작성"  
정도로 수정하는 것이 좋아 보이는군요.  
<배용욱 시작>  부분은 우측에 보시면 `Assignees` 부분이 있는데요, 이게 이 작업을 누가 수행할지를 지정하는 부분입니다.  
`assign yourself`를 누르면 자동으로 자기 자신이 등록되니 참고 하세요!

**Comment by yongwookbae** [comment]
![KakaoTalk_20190606_165625169](https://user-images.githubusercontent.com/50331109/59016422-26376e80-887c-11e9-8953-6f12a69e2bc5.jpg)

**Comment by umbum** [comment]
반품 시 결제 취소를 진행하려면 PAYMENT에 대한 정보도 가지고 와야 할 것으로 보입니다.

**Comment by yongwookbae** [comment]
![KakaoTalk_20190607_032723735](https://user-images.githubusercontent.com/50331109/59060092-48aca480-88db-11e9-8ca8-9fc678a19b07.jpg)
